<?php

namespace AppBundle\Repository;

/**
 * TimeIntervalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeIntervalRepository extends \Doctrine\ORM\EntityRepository
{
}
